export const INITIALIZE_MAP = "INITIALIZE_MAP";
export const SET_DATA_FEATURES = "SET_DATA_FEATURES";
export const SET_FILTERED_FEATURES = "SET_FILTERED_FEATURES";
export const SET_DRAW = "SET_DRAW";

